### ISSUE TITLE
having trouble with 2nd sentence in this footnote

### ISSUE THREAD

**Issue by vmarchman** [langcog/wordbank-paper#1]
The only exception to this policy currently is that we allow users to see responses across forms for individual words, in the Item Trajectories analysis. Since many of the concerns about comparing across forms center around the different items on each form, within-item analyses are likely less problematic.

Not sure what "within-item analyses" is referring to....

**Comment by mcfrank** [comment]
Thanks for checking on the draft. I agree that's a little terse. I actually
haven't finished a second read through and still have a bit more work to do
- maybe I can punt to you in a few days? Sorry to be slow to revise,

**Comment by vmarchman** [comment]
Oh sorry to jump the gun!
