### ISSUE TITLE
forms vs. instruments, make consistent

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank-paper#3]

**Comment by mcfrank** [comment]
I couldn't eliminate one or the other. I tried to use "instrument" to refer to the package - e.g. using an instrument  to measure early language - and "form" to refer to the actual piece of paper, e.g. "the form is composed of xyz questions." Does that seem reasonable?

**Comment by vmarchman** [comment]
Yes, that seems reasonable to me.

-vm

On Sat, Dec 5, 2015 at 2:47 PM, Michael Frank notifications@github.com
wrote:

> I couldn't eliminate one or the other. I tried to use "instrument" to
> refer to the package - e.g. using an instrument to measure early language -
> and "form" to refer to the actual piece of paper, e.g. "the form is
> composed of xyz questions." Does that seem reasonable?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/langcog/wordbank-paper/issues/3#issuecomment-162254666
> .

## 

---

Virginia A. Marchman, Ph.D.
marchman@stanford.edu
Research Associate
Center for Infant Studies
Psychology
Stanford University
Stanford, CA  94305
650-723-1257

---

**Comment by mcfrank** [comment]
Great - I guess the big question then is whether I should wait on the
Italians to resubmit or not...

Mike

**Comment by dyurovsky** [comment]
Sorry, I must have missed the context here. Why not just always use
instrument?

If that doesn't make sense, Mike I think your solution seems reasonable.

Dan

**Comment by vmarchman** [comment]
Right.  I was going to ask about that.....

no word yet, eh?  argh.

**Comment by mcfrank** [comment]
I guess I changed most of them to instrument, but consider these:

"The \texttt{common} tables store data that is shared between CDI
instruments, including information about children, administrations
(individual instances of a form being filled out for a child) ... "

and

"The general philosophy of the CDI has been summarized as `adaptation, not
translation'' \cite{dale2015}. In other words, CDIs are a useful tool for
many languages, but the forms differ between languages---words and even
whole sections are added, dropped, and modified to ensure that the form
captures the details of the particular language for which it is designed.
To date, more than 60 adaptations of the original English CDI have been
documented \cite{dale2011}. These forms vary widely, including differences
in length and intended age range. Some forms include hundreds of items more
than the original 680 words on the English Words \& Sentences form; others
are so-called`short forms'' and include only a hundred or a few hundred
carefully selected words. "

Both cases felt weird to swap, no?

Mike

**Comment by dyurovsky** [comment]
Ah, I see. Yeah "short instruments" probably no good...
